changeLogFile=changelog-master.xml
url=jdbc:postgresql://host.docker.internal:5432/lsm_db
# url=jdbc:postgresql://localhost:5432/lsm_db
username=<username>
password=<password>
classpath=./postgresql-42.7.3.jar
# driver=org.postgresql.Driver
# classpath=postgresql-42.7.1.jar